CREATE TABLE USR(
    ID SERIAL PRIMARY KEY,
    NAME CHAR(8)
);

CREATE TABLE ROLES(
    ID SERIAL PRIMARY KEY,
    NAME CHAR(8) UNIQUE
);

CREATE TABLE USR_ROLE(
    ID_USER INT REFERENCES USR(ID) ON DELETE CASCADE,
    ID_ROLES INT REFERENCES ROLES(ID) ON DELETE CASCADE
);